# -*- coding: utf-8 -*-
"""Expense_Tracker.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a8EhmbuIdWIGbUhcWxgC6cuL-R8lMPRe
"""

import datetime

def add_expense():
    amount = float(input("Enter amount spent: ₹"))
    category = input("Enter category (Food/Travel/Shopping/Other): ")
    date = datetime.date.today().strftime("%d-%m-%Y")

    with open("expenses.txt", "a") as file:
        file.write(f"{date}, {category}, ₹{amount}\n")

    print("Expense added successfully!")

def view_expenses():
    try:
        with open("expenses.txt", "r") as file:
            data = file.read()
            if data == "":
                print("No expenses recorded yet.")
            else:
                print("\n----- Your Expenses -----")
                print(data)
    except FileNotFoundError:
        print("No expense file found. Add an expense first.")

def total_expenses():
    total = 0
    try:
        with open("expenses.txt", "r") as file:
            for line in file:
                parts = line.strip().split(",")
                amount = float(parts[2].replace("₹", ""))
                total += amount
        print(f"\nTotal Amount Spent: ₹{total}")
    except FileNotFoundError:
        print("No expenses available to calculate.")

while True:
    print("\n==== Expense Tracker Menu ====")
    print("1. Add Expense")
    print("2. View All Expenses")
    print("3. Calculate Total Expenses")
    print("4. Exit")

    choice = input("Enter your choice: ")

    if choice == "1":
        add_expense()
    elif choice == "2":
        view_expenses()
    elif choice == "3":
        total_expenses()
    elif choice == "4":
        print("Thank you for using Expense Tracker!")
        break
    else:
        print("Invalid choice! Please try again.")